### ISSUE TITLE
Nuxt Error

### ISSUE THREAD

**Issue by stevepop** [potato4d/nuxt-maintenance-mode#37]
I installed nuxt-maintenance-mode today and followed the instructions. When I however executed `yarn dev` on my project, I got the error below;

<img width="559" alt="nuxt-maintenance-module" src="https://user-images.githubusercontent.com/526063/55907613-1e868100-5bcf-11e9-90f0-64b86d8649b2.png">

Any Idea how this issue can be resolved?

Thanks

**Comment by potato4d** [comment]
thanks! iwill confirm it

**Comment by potato4d** [comment]
@stevepop 
Could you create a minimal repository or codesandbox URL to reproduce?
